name: ObsidianCage
version: '1.0.0'
main: yernaz.obsidianCage.ObsidianCage
api-version: '1.21'
authors: [ Yernaz ]

commands:
  trap:
    description: Gives you the Trap item
    usage: /trap [amount]
    permission: obsidiancage.trap
permissions:
  obsidiancage.trap:
    default: op

